"""
Schemas for the agent API v1.

This module defines the data schemas used by the agent API version 1.
"""

from pydantic import BaseModel, Field
from typing import Optional

class MessageRequest(BaseModel):
    """Request schema for processing a message."""
    session_id: str = Field(..., description="Unique identifier for the session")
    user_input: str = Field(..., description="User input message to be processed")  

class MessageResponse(BaseModel):
    """Response schema for processed messages."""
    response: str = Field(..., description="Response message generated by the agent")